# Generated by Django 5.2.17 on 2026-10-06 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLookupCache',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('payload', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapProviderGate',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('next_at', models.DateTimeField()),
                ('lease_until', models.DateTimeField()),
                ('lease', models.UUIDField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapQuota',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('window_started_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('attempts__lte', 10)), name='map_quota_max_10')],
            },
        ),
    ]
