# Generated by Django 5.2.17 on 2026-09-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('sayuran', 'Sayuran'), ('buah', 'Buah'), ('protein_hewani', 'Protein Hewani'), ('protein_nabati', 'Protein Nabati'), ('bahan_pokok', 'Bahan Pokok'), ('lainnya', 'Lainnya')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('liter', 'liter'), ('buah', 'buah'), ('ikat', 'ikat'), ('butir', 'butir'), ('papan', 'papan'), ('kotak', 'kotak'), ('bungkus', 'bungkus'), ('botol', 'botol'), ('pak', 'pak')], max_length=20)),
                ('location', models.CharField(choices=[('chiller', 'Kulkas Bawah (Chiller)'), ('freezer', 'Freezer'), ('suhu_ruang', 'Suhu Ruang'), ('lemari_kering', 'Lemari Kering')], max_length=20)),
                ('shelf_life_days', models.PositiveSmallIntegerField()),
                ('estimated_expires_on', models.DateField()),
                ('source', models.CharField(choices=[('ocr', 'Struk'), ('manual', 'Manual')], max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['estimated_expires_on', 'id'],
            },
        ),
    ]
