# Generated by Django 5.2.17 on 2026-10-01 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_ingredient_calories_method_text'),
        ('pantry', '0005_pantry_name_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitem',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.ingredient'),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='starting_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='location',
            field=models.CharField(blank=True, choices=[('chiller', 'Kulkas Bawah (Chiller)'), ('freezer', 'Freezer'), ('suhu_ruang', 'Suhu Ruang'), ('lemari_kering', 'Lemari Kering')], default='suhu_ruang', max_length=20),
        ),
    ]
