# Generated by Django 5.2.17 on 2026-10-05 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_ingredient_calories_method_text'),
        ('pantry', '0008_pantryitem_user_pantrynamecorrection_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NameResolution',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('normalized_name', models.CharField(max_length=255)),
                ('lease', models.UUIDField(null=True)),
                ('expires_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PantryLLMUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('kind', models.CharField(choices=[('photo', 'Photo'), ('names', 'Names')], max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PantryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('in', 'Masuk'), ('correction', 'Koreksi'), ('move', 'Pindah'), ('discard', 'Dibuang'), ('consume', 'Dipakai')], max_length=20)),
                ('quantity_before', models.DecimalField(decimal_places=6, max_digits=14)),
                ('quantity_after', models.DecimalField(decimal_places=6, max_digits=14)),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PantryOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField()),
                ('kind', models.CharField(max_length=20)),
                ('payload_hash', models.CharField(max_length=64)),
                ('response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='base_unit',
            field=models.CharField(choices=[('g', 'g'), ('ml', 'ml'), ('pcs', 'pcs')], default='pcs', max_length=3),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='conversion_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='expiry_source',
            field=models.CharField(choices=[('label', 'Label kemasan'), ('manual', 'Manual'), ('estimate', 'Estimasi'), ('unknown', 'Belum diketahui')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='grams_per_unit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='pack_weight_g',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AddConstraint(
            model_name='pantryitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='pantry_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='pantryitem',
            constraint=models.CheckConstraint(condition=models.Q(('pack_weight_g__isnull', True), ('pack_weight_g__gt', 0), _connector='OR'), name='pantry_pack_weight_positive'),
        ),
        migrations.AddConstraint(
            model_name='pantryitem',
            constraint=models.CheckConstraint(condition=models.Q(('grams_per_unit__isnull', True), ('grams_per_unit__gt', 0), _connector='OR'), name='pantry_conversion_positive'),
        ),
        migrations.AddField(
            model_name='nameresolution',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ingredient'),
        ),
        migrations.AddField(
            model_name='pantryllmusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pantrymovement',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='pantry.pantryitem'),
        ),
        migrations.AddField(
            model_name='pantryoperation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pantrymovement',
            name='operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pantry.pantryoperation'),
        ),
        migrations.AddConstraint(
            model_name='pantryllmusage',
            constraint=models.UniqueConstraint(fields=('user', 'day', 'kind'), name='pantry_daily_usage_unique'),
        ),
        migrations.AddConstraint(
            model_name='pantryllmusage',
            constraint=models.CheckConstraint(condition=models.Q(('attempts__lte', 10)), name='pantry_daily_usage_limit'),
        ),
        migrations.AddConstraint(
            model_name='pantryoperation',
            constraint=models.UniqueConstraint(fields=('user', 'key'), name='pantry_operation_unique'),
        ),
    ]
