# Generated by Django 5.2.17 on 2026-10-05 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0010_backfill_batches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantrymovement',
            name='operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pantry.pantryoperation'),
        ),
    ]
