# Generated by Django 5.2.17 on 2026-10-05 13:41

from django.db import migrations, models


def classify_legacy_dates(apps, schema_editor):
    Batch = apps.get_model("pantry", "PantryItem")
    Movement = apps.get_model("pantry", "PantryMovement")
    alias = schema_editor.connection.alias
    migrated = Movement.objects.using(alias).filter(snapshot__migration=True).values("batch_id")
    Batch.objects.using(alias).filter(
        pk__in=migrated,
        expiry_source="unknown",
        estimated_expires_on__isnull=False,
        version=1,
    ).update(expiry_source="legacy")


def unclassify_legacy_dates(apps, schema_editor):
    Batch = apps.get_model("pantry", "PantryItem")
    Movement = apps.get_model("pantry", "PantryMovement")
    alias = schema_editor.connection.alias
    migrated = Movement.objects.using(alias).filter(snapshot__migration=True).values("batch_id")
    Batch.objects.using(alias).filter(pk__in=migrated, expiry_source="legacy").update(
        expiry_source="unknown"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("pantry", "0011_alter_pantrymovement_operation"),
    ]

    operations = [
        migrations.AddField(
            model_name="pantrynamecorrection",
            name="confirmed_by_user",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pantryitem",
            name="expiry_source",
            field=models.CharField(
                choices=[
                    ("legacy", "Tanggal lama (periksa label)"),
                    ("label", "Label kemasan"),
                    ("manual", "Manual"),
                    ("estimate", "Estimasi"),
                    ("unknown", "Belum diketahui"),
                ],
                default="unknown",
                max_length=10,
            ),
        ),
        migrations.RunPython(classify_legacy_dates, unclassify_legacy_dates),
    ]
