# Generated by Django 5.2.17 on 2026-10-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0012_pantrynamecorrection_confirmed_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantrymovement',
            name='consumed_grams',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=26, null=True),
        ),
        migrations.AddConstraint(
            model_name='pantrymovement',
            constraint=models.CheckConstraint(condition=models.Q(('consumed_grams__isnull', True), ('consumed_grams__gte', 0), _connector='OR'), name='pantry_consumed_grams_nonnegative'),
        ),
    ]
