# Generated by Django 5.2.17 on 2026-10-05 15:43

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_ingredient_allergen_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthRateBucket',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targets', models.JSONField(default=apps.accounts.models.default_targets)),
                ('meal_types', models.JSONField(default=apps.accounts.models.default_meals)),
                ('servings', models.PositiveSmallIntegerField(default=2)),
                ('allergens', models.JSONField(default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('avoided_ingredients', models.ManyToManyField(blank=True, to='catalog.ingredient')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('servings__gte', 1), ('servings__lte', 10)), name='profile_servings_valid')],
            },
        ),
    ]
