# Generated by Django 5.2.17 on 2026-10-01 12:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestTrial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('window_started_at', models.DateTimeField(blank=True, null=True)),
                ('successful_uses', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('successful_uses__lte', 3)), name='guest_trial_max_3')],
            },
        ),
    ]
