# Generated by Django 5.2.17 on 2026-10-04 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_planner', '0001_initial'),
        ('catalog', '0002_ingredient_calories_method_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('saved', 'Tersimpan')], default='draft', max_length=10)),
                ('title', models.CharField(default='Rencana Makan Saya', max_length=100)),
                ('starts_on', models.DateField()),
                ('inputs', models.JSONField()),
                ('snapshot', models.JSONField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('source_version', models.PositiveIntegerField(blank=True, null=True)),
                ('last_saved_version', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_saved_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_from_drafts', to='budget_planner.budgetplan')),
                ('source_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editing_drafts', to='budget_planner.budgetplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PlannedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField()),
                ('scheduled_on', models.DateField()),
                ('meal_type', models.CharField(max_length=20)),
                ('servings', models.PositiveSmallIntegerField()),
                ('snapshot', models.JSONField()),
                ('status', models.CharField(choices=[('planned', 'Belum Masak'), ('cooked', 'Sudah Masak'), ('skipped', 'Dilewati')], default='planned', max_length=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='budget_planner.budgetplan')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.recipe')),
            ],
            options={
                'ordering': ['day', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='PlanPreview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('draft_version', models.PositiveIntegerField(blank=True, null=True)),
                ('inputs', models.JSONField()),
                ('snapshot', models.JSONField()),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previews', to='budget_planner.budgetplan')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_grams', models.DecimalField(decimal_places=3, max_digits=14)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('snapshot', models.JSONField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.ingredient')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to='budget_planner.budgetplan')),
            ],
        ),
        migrations.AddConstraint(
            model_name='budgetplan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('user',), name='one_planner_draft_per_user'),
        ),
        migrations.AddConstraint(
            model_name='plannedmeal',
            constraint=models.UniqueConstraint(fields=('plan', 'day', 'meal_type'), name='one_meal_per_plan_slot'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglistitem',
            constraint=models.UniqueConstraint(fields=('plan', 'ingredient'), name='one_ingredient_per_plan_list'),
        ),
    ]
