# Generated by Django 5.2.17 on 2026-10-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_planner', '0002_budgetplan_plannedmeal_planpreview_shoppinglistitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpreview',
            name='draft_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
