# Generated by Django 5.2.17 on 2026-10-05 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('budget_planner', '0003_preview_draft_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPreviewQuota',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('window_started_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('attempts__lte', 20)), name='preview_quota_max_20')],
            },
        ),
    ]
