# Generated by Django 5.2.17 on 2026-10-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_planner', '0004_preview_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='added_to_pantry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
