# Generated by Django 5.2.17 on 2026-10-06 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget_planner', '0004_preview_quota'),
        ('catalog', '0004_recipe_allergen_reviewed_and_more'),
        ('pantry', '0012_pantrynamecorrection_confirmed_by_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=255)),
                ('servings', models.PositiveSmallIntegerField()),
                ('snapshot', models.JSONField()),
                ('cooked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pantry.pantryoperation')),
                ('planned_meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget_planner.plannedmeal')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cooked_at', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('planned_meal__isnull', False)), fields=('planned_meal',), name='one_cooking_per_planned_meal'), models.CheckConstraint(condition=models.Q(('servings__gte', 1), ('servings__lte', 10)), name='cooking_servings_valid')],
            },
        ),
        migrations.CreateModel(
            name='RecipeFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'recipe'), name='recipe_favorite_unique')],
            },
        ),
    ]
