# Generated by Django 5.2.17 on 2026-10-06 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0013_pantrymovement_consumed_grams_and_more'),
        ('recipe_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookinghistory',
            name='operation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='pantry.pantryoperation'),
        ),
    ]
