"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import ipaddress
import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
FIXTURE_DIRS = [BASE_DIR / "data" / "fixtures"]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

PRODUCTION = os.getenv("PRODUCTION", "False").lower() == "true"
# Opt-in per deployment; local development stays available by default.
MAINTENANCE_MODE = os.getenv("MAINTENANCE_MODE", "false").strip().lower() == "true"
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if PRODUCTION:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY wajib diatur di environment PWS.")
    SECRET_KEY = "django-insecure-hanya-untuk-pengembangan-lokal"

DEBUG = not PRODUCTION
SESSION_COOKIE_SECURE = PRODUCTION
CSRF_COOKIE_SECURE = PRODUCTION
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "modul5"
AUTHENTICATION_BACKENDS = ["apps.accounts.backends.UsernameOrEmailBackend"]
# Empty by default. Set only to the actual, verified PWS reverse-proxy CIDRs.
AUTH_TRUSTED_PROXY_CIDRS = [
    value.strip() for value in os.getenv("AUTH_TRUSTED_PROXY_CIDRS", "").split(",") if value.strip()
]
try:
    for proxy_cidr in AUTH_TRUSTED_PROXY_CIDRS:
        network = ipaddress.ip_network(proxy_cidr)
        if network.prefixlen == 0:
            raise ValueError("Daftar proxy tidak boleh mempercayai seluruh internet.")
except ValueError as error:
    raise ImproperlyConfigured(
        "AUTH_TRUSTED_PROXY_CIDRS harus berisi CIDR proxy terpercaya."
    ) from error

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "alfredo-nathaniel-takarkuy.pws.cs.ui.ac.id",
]
CSRF_TRUSTED_ORIGINS = [
    "https://alfredo-nathaniel-takarkuy.pws.cs.ui.ac.id",
]

# Application definition

INSTALLED_APPS = [
    "apps.accounts",
    "apps.catalog",
    "apps.budget_planner",
    "apps.pantry",
    "apps.recipe_book",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "apps.accounts.middleware.MaintenanceMiddleware",
    "apps.pantry.uploads.ReceiptUploadMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "apps.accounts.middleware.AuthRateLimitMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database configuration
if PRODUCTION:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PASSWORD"),
            "HOST": os.getenv("DB_HOST"),
            "PORT": os.getenv("DB_PORT"),
            "OPTIONS": {
                "options": f"-c search_path={os.getenv('SCHEMA', 'public')}",
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
            "OPTIONS": {"transaction_mode": "IMMEDIATE", "timeout": 20},
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        "NAME": "apps.accounts.validators.UppercaseNumberSymbolValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "id"

# Only sanitized counts/tokens/timing, never provider request bodies.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"pantry_ai_console": {"class": "logging.StreamHandler"}},
    "loggers": {
        "apps.pantry.ai_usage": {
            "handlers": ["pantry_ai_console"],
            "level": "INFO",
            "propagate": False,
        }
    },
}

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
WHITENOISE_USE_FINDERS = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
