# Generated by Django 5.2.17 on 2026-09-28 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=40)),
                ('base_unit', models.CharField(max_length=20)),
                ('calories_per_100g', models.FloatField(blank=True, null=True)),
                ('protein_per_100g', models.FloatField(blank=True, null=True)),
                ('carbs_per_100g', models.FloatField(blank=True, null=True)),
                ('fat_per_100g', models.FloatField(blank=True, null=True)),
                ('nutrition_source', models.CharField(blank=True, max_length=255)),
                ('nutrition_source_id', models.CharField(blank=True, max_length=100)),
                ('nutrition_verified', models.BooleanField(default=False)),
                ('calories_method', models.CharField(blank=True, max_length=255)),
                ('nutrition_source_url', models.URLField(blank=True, max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('base_servings', models.PositiveIntegerField(blank=True, null=True)),
                ('meal_type', models.CharField(blank=True, max_length=40)),
                ('instructions', models.TextField(blank=True)),
                ('is_plannable', models.BooleanField(default=False)),
                ('missing_data_reason', models.TextField(blank=True)),
                ('source', models.CharField(max_length=255)),
                ('source_url', models.URLField(max_length=600)),
                ('raw_ingredients', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientAlias',
            fields=[
                ('alias_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=255)),
                ('raw_name', models.CharField(max_length=255)),
                ('mapping_status', models.CharField(max_length=50)),
                ('ingredient', models.ForeignKey(db_column='ingredient_code', on_delete=django.db.models.deletion.PROTECT, to='catalog.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientShelfLife',
            fields=[
                ('shelf_life_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('storage_location', models.CharField(max_length=30)),
                ('min_days', models.PositiveIntegerField()),
                ('max_days', models.PositiveIntegerField()),
                ('warning_days', models.PositiveIntegerField()),
                ('starting_event', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=255)),
                ('source_record_id', models.CharField(blank=True, max_length=100)),
                ('source_url', models.URLField(max_length=600)),
                ('source_recorded_at', models.DateField(blank=True, null=True)),
                ('source_license', models.CharField(blank=True, max_length=255)),
                ('source_duration', models.CharField(max_length=100)),
                ('days_conversion_method', models.CharField(max_length=255)),
                ('shelf_life_status', models.CharField(max_length=100)),
                ('mapping_note', models.TextField(blank=True)),
                ('ingredient', models.ForeignKey(db_column='ingredient_code', on_delete=django.db.models.deletion.PROTECT, to='catalog.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('recipe_ingredient_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(max_length=30)),
                ('is_optional', models.BooleanField(default=False)),
                ('quantity_status', models.CharField(max_length=40)),
                ('raw_text', models.TextField(blank=True)),
                ('source', models.CharField(max_length=255)),
                ('ingredient', models.ForeignKey(db_column='ingredient_code', on_delete=django.db.models.deletion.PROTECT, to='catalog.ingredient')),
                ('recipe', models.ForeignKey(db_column='recipe_code', on_delete=django.db.models.deletion.CASCADE, to='catalog.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeTag',
            fields=[
                ('recipe_tag_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=255)),
                ('recipe', models.ForeignKey(db_column='recipe_code', on_delete=django.db.models.deletion.CASCADE, to='catalog.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('conversion_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=30)),
                ('gram_equivalent', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(max_length=255)),
                ('source_url', models.URLField(blank=True, max_length=600)),
                ('conversion_status', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True)),
                ('ingredient', models.ForeignKey(db_column='ingredient_code', on_delete=django.db.models.deletion.PROTECT, to='catalog.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientPrice',
            fields=[
                ('price_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('price_rupiah', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=100)),
                ('recorded_at', models.DateField()),
                ('source', models.CharField(max_length=255)),
                ('source_url', models.URLField(max_length=600)),
                ('source_recorded_at', models.DateField(blank=True, null=True)),
                ('source_license', models.CharField(blank=True, max_length=255)),
                ('source_commodity_name', models.CharField(max_length=255)),
                ('price_status', models.CharField(max_length=50)),
                ('ingredient', models.ForeignKey(db_column='ingredient_code', on_delete=django.db.models.deletion.PROTECT, to='catalog.ingredient')),
            ],
            options={
                'indexes': [models.Index(fields=['ingredient', 'region', 'recorded_at'], name='catalog_ing_ingredi_676c10_idx')],
            },
        ),
    ]
