# Generated by Django 5.2.17 on 2026-10-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_ingredient_calories_method_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="allergen_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="allergen_source_url",
            field=models.URLField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="allergen_status",
            field=models.CharField(
                choices=[
                    ("unknown", "Belum ditinjau"),
                    ("reviewed", "Ditinjau berdasarkan jenis bahan"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="allergens",
            field=models.JSONField(default=list),
        ),
    ]
