# Generated by Django 5.2.17 on 2026-10-06 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_ingredient_allergen_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='allergen_reviewed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instruction_review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instruction_reviewed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instruction_status',
            field=models.CharField(choices=[('source_ok', 'Sumber disetujui'), ('authored_reviewed', 'Panduan tim ditinjau'), ('withheld', 'Ditahan')], db_index=True, default='withheld', max_length=20),
        ),
        migrations.CreateModel(
            name='RecipeAllergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(db_index=True, max_length=30)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergen_groups', to='catalog.recipe')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('recipe', 'group'), name='recipe_allergen_unique')],
            },
        ),
    ]
